workInfo:
  title: "Preludio BWV 1006"
  fullTitle: "Partita for Violin No. 3 (Bach)"
  composer: "J.S. Bach"
  workId: "bwv1006"
  movementName: "Preludio"
  externalURL: "https://en.wikipedia.org/wiki/Partita_for_Violin_No._3_(Bach)"

files:
  svgPath: "bwv1006_optimized.svg"
  notesPath: "bwv1006_json_notes.json"
  audioPath: "bwv1006202505211530.wav"
  
musicalStructure:
  totalDurationSeconds: 207.10
  totalBars: 138
  visualLeadTimeSeconds: 0.2
