workInfo:
  title: "Preludio BWV 1006"
  fullTitle: "Partita for Violin No. 3 (Bach)"
  composer: "J.S. Bach"
  workId: "bwv1006"
  movementName: "Preludio"
  externalURL: "https://en.wikipedia.org/wiki/Partita_for_Violin_No._3_(Bach)"

files:
  audioPath: "bwv1006202505211530.mp3"
  
musicalStructure:
  totalDurationSeconds: 206.88
  totalMeasures: 138
  visualLeadTimeSeconds: 0

measureHighlighters:
  line-breaks:
    name: "Start of Group"  # Display name for UI
    type: conditional
    colors: ["#e0d2bf", "#f2ede4"]
    opacity: 1
    condition:
      type: line-starts
      bars: [1, 3, 7, 9, 17, 29, 33, 39, 43, 67, 79, 83, 90, 93, 99, 102, 109, 113, 119, 123, 130, 138]
